### ISSUE TITLE
Серьезный баг: После изменения кода реализации шагов (внутри обработки) не подхватываются эти изменения

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#14]
Серьезный баг: После изменения кода реализации шагов (внутри обработки) не подхватываются эти изменения
и Предприятие приходится перезапускать.

такое впечатление, что где-то циклические ссылки остаются, у меня было такое при разработке УФ для хЮнит
симптом - я убрал в епф-файле использование Предупреждение, поставил Сообщить, 
вернулся в Предприятие, перезапускаю тестирование, а все равно выдается предупреждение :(
приходится предприятие перезапусктаь

**Comment by Pr-Mex** [comment]
Скажи на каком релизе 1С это воспроизводится. На 8.3.6 у меня не получилось.

**Comment by artbear** [comment]
8.3.4.408
Попробуй поменять несколько раз, дообавив разные сообщения/предупреждения и просто позапускать тестирование, не закрывая обработку тестирования.
