### ISSUE TITLE
Сделать основной интерфейс запуска тестов в виде дерева.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavoir#17]
Примерный вид:
![image](https://cloud.githubusercontent.com/assets/8627416/7816042/b3b1ca20-03d4-11e5-8a24-4e5f71a38359.png)

**Comment by allustin** [comment]
оставлю пример из Eclipse в качестве точки отсчета для дерева

![2015-07-05 12-29-59](https://cloud.githubusercontent.com/assets/55323/8511133/b8b7a7a8-2312-11e5-9b42-847112323e68.png)

**Comment by Pr-Mex** [comment]
На данный момент дерево сделано и работает. Закрываю.
