### ISSUE TITLE
Precomit требует, чтобы обязательно в папке hooks лежали нужные файлы, хотя в командной строке они не указаны.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavoir#28]
Например при команде
**python C:\Rep\vanessa-behavoir\vendor\precommit1c\pyv8unpack.py --compile "C:\Temp\feature\step_definitions\src\AdditionTest" "C:\Temp\feature\step_definitions\AdditionTest.epf"**

команда не отработает, если нет папки **C:\Rep\vanessa-behavoir\.git\hooks\ibService**, хотя она и не должна требоваться.

**Comment by allustin** [comment]
precommit жестко ориентирован по структуре на работу в режиме хуков

https://github.com/xDrivenDevelopment/precommit1c/blob/8bf2e2a8dcdb9bac01c7c013479fa3a6e89842f6/pyv8unpack.py#L209

поэтому - либо повторять функционал precommit и напрямую использовать v8reader, либо добавлять поддержку в precoomit работы НЕ в режиме hook'а

**Comment by allustin** [comment]
https://github.com/xDrivenDevelopment/precommit1c/issues/33 - дополнительное обсуждение

**Comment by Pr-Mex** [comment]
Надо проверить на чистой машине, воспроизводится ли ошибка сейчас.

**Comment by Pr-Mex** [comment]
Проверено в рамках #45. Всё ок.
