### ISSUE TITLE
ОФ+УФ: Выдается ошибка при несвязанности каталогов проекта и каталога фич

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#3]
ОФ+УФ: Выдается ошибка при несвязанности каталогов проекта и каталога фич
УФ:
![image](https://cloud.githubusercontent.com/assets/2920817/7631027/61044908-fa45-11e4-9b32-d0f3bb897aaf.png)
ОФ:
![image](https://cloud.githubusercontent.com/assets/2920817/7631038/75db4e44-fa45-11e4-81fa-ffe15f6235d6.png)

**Comment by Pr-Mex** [comment]
Решено.
