### ISSUE TITLE
УФ: не тестируются файлы фич с русскими именами

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#4]
УФ: не тестируются файлы фич с русскими именами
Например, у меня есть файл C:\Projects\vanessa-behavoir\features\Test\Пример_631.feature 
![image](https://cloud.githubusercontent.com/assets/2920817/7631087/3bad14fe-fa46-11e4-875b-92474776b346.png)

ошибка:
`No such file or directory - C:/Projects/vanessa-behavoir/features/Test/¦ßTÀ¦¬¦-¦¦TÀ_631.feature. Please create a C:/Projects/vanessa-behavoir/features/Test/¦ßTÀ¦¬¦-¦¦TÀ_631.feature directory to get started. (Errno::ENOENT)`

**Comment by Pr-Mex** [comment]
Cucumber больше не используется. Проблем с русскими именами файлов нет.
