### ISSUE TITLE
Грамматика файла

### ISSUE THREAD

**Issue by wwall** [silverbulleters/vanessa-behavoir#46]
Грамматика файла описания features есть? 
Из кода не очень понятно что во что преобразуется.

**Comment by allustin** [comment]
Используем классическую вот отсюда https://github.com/cucumber/cucumber/wiki/Spoken-languages

А точнее отсюда 

https://github.com/cucumber/cucumber-ruby/blob/master/examples/i18n/ru/features/addition.feature
https://github.com/cucumber/cucumber-ruby/blob/master/examples/i18n/ru/features/consecutive_calculations.feature
https://github.com/cucumber/cucumber-ruby/blob/master/examples/i18n/ru/features/division.feature

В итоге по каждому шагу сценария получаем имя процедуры с параметром

Из такой фичи
https://github.com/silverbulleters/vanessa-behavoir/blob/develop/features/Buh30/Avance.feature

Генерируется следующий код

```
//существует договор 'тестовый договор Контрагента 1' с датой договора 01.01.2014
//@СуществуетДоговорСДатойДоговора(Парам01Строка,Парам02Дата)
Процедура СуществуетДоговорСДатойДоговора(ИмяДоговора,ДатаДоговора) Экспорт
	
	Если Контекст.Свойство("Договор") Тогда
```

**Comment by allustin** [comment]
@Pr-Mex надо будет написать простую инструкцию к версии 0.9 #47

P.S. Эту задачу пока закрою
