### ISSUE TITLE
Проблема с парсингом шагов

### ISSUE THREAD

**Issue by hawk911** [silverbulleters/vanessa-behavoir#49]
* И я спозиционировался на документе "Заявка на звонок".

На таком шаге происходит не корректная генерация снипета, должен быть только один параметр. 

Процедура ЯСпозиционировалсяНаДокументе(Парам01Строка,Парам02Число) Экспорт
	ВызватьИсключение "Не реализовано.";
КонецПроцедуры

**Comment by Pr-Mex** [comment]
Закрываю.
