### ISSUE TITLE
Добавьте лицензии и упоминания об xUnitFor1C и precommit1c

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#54]
Предлагаю добавить лицензии xUnitFor1C + precommit1c и упоминание об xUnitFor1C+precommit1c в readme.md
т.к. идет использование инструментов от xUnitFor1C (ассерты, генерация/загрузка данных и прочее).

**Comment by allustin** [comment]
Пока не готовы так сделать, в связи с тем что: 

* архитектура продукта пока не стабилизирована - скорее всего asserts будут переработаны на свои (возможно, но не обязательно).
* лицензия на блок ассертов пока не ясна - изначально блок "ассеротов" вроде как базировался на модуле Я.Тест. И совершенно непонятно кого указывать в качестве авторов. 
* precommit1C используется в качестве подмодуля и дополнительной лицензии не требует - это видно и так. - насколько мне известно

В целом - ситуация с лицензиями пока не прозрачна. поэтому мы использовали способ публикации статьи на http://habrahabr.ru/post/252473/ c указанием исторического развития

**Comment by allustin** [comment]
Дополнительно:

* прямая отсылка к используемому коду из xUnit https://github.com/silverbulleters/vanessa-behavoir/blob/develop/src/vanessa-behavior/ObjectModule.txt#L6

* генератор данных мы сейчас используем вот такой https://github.com/silverbulleters/vanessa-base-init - так что непонятно что имеется ввиду под - генерация/загрузка данных и прочее

**Comment by allustin** [comment]
еще одно упоминание портированного кода https://github.com/silverbulleters/vanessa-behavoir/blob/develop/src/vanessa-behavior/ObjectModule.txt#L590

Что ещё необходимо пока непонятно.

**Comment by Cujoko** [comment]
Я воздержусь.

**Comment by nixel2007** [comment]
@Cujoko видимо, ты имел ввиду вот эту ветку диалога, да? https://github.com/xDrivenDevelopment/precommit1c/issues/67

**Comment by Cujoko** [comment]
@nixel2007 Несомненно. Странно как-то не в ту ветку написал.
