### ISSUE TITLE
Схема работы с исходниками epf-файла

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#6]
Схема работы с исходниками epf-файла (совместно с @Pr-Mex)
Сейчас необходимо после генерации epf-файла необходимо сделать коммит в гит-репозитарий, настроенный для precommit1c.
Это плохая юзабельность для пользователя.

Предлагается следующий вариант:
- считать precommit1c необходимой часть продукта
- выполнять автоматический разбор epf-файла на исходники перед запуском тестов.
  - если исходников нет, генерить исходники автоматом
  - если дата/время исходников меньше даты/времени epf-файла, также генерить исходники автоматом

**Comment by Pr-Mex** [comment]
Решено. Было принято решение отказаться от требования коммитить в git созданные обработки, иначе не происходил запуск тестов.
Теперь получение исходников обработок происходит не лету.
