### ISSUE TITLE
Переименовать реквизит "Каталог проекта" в "Каталог инструментов"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavoir#7]
Переименовать реквизит "Каталог проекта" в "Каталог инструментов" (совместно с @Pr-Mex )
![image](https://cloud.githubusercontent.com/assets/2920817/7631675/ee8957ca-fa4d-11e4-9de2-e4f077134ea3.png)

**Comment by Pr-Mex** [comment]
Решено.
